global:
  scrape_interval: 5s  # Collect metrics every 5 seconds
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'reward-calculation-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['reward-calculation-app-instance-1:8080', 'reward-calculation-app-instance-2:8080']
  - job_name: 'reward-payment-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['reward-payment-app-instance-1:8090', 'reward-payment-app-instance-2:8090']
