networks:
  tim-network:

services:
  reward-calculation-db:
    networks: [tim-network]
    container_name: reward-calculation-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Lalka123
      MYSQL_DATABASE: reward_calculation_db
    ports:
      - "3000:3306"

  reward-payment-db:
    networks: [tim-network]
    container_name: reward-payment-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Lalka123
      MYSQL_DATABASE: reward_payment_db
    ports:
      - "3001:3306"

  reward-calculation-app:
    networks: [tim-network]
    container_name: reward-calculation-app
    image: reward-calculation-app:1.0.1
    ports:
      - "8080:8080"
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    command: ["sh", "-c", "chmod +x /wait-for-it.sh && /wait-for-it.sh reward-calculation-db:3306 --timeout=30 -- java -jar /reward-calculation-app.jar --spring.profiles.active=mysql-container"]
    depends_on:
      - reward-calculation-db

  reward-payment-app:
    networks: [tim-network]
    container_name: reward-payment-app
    image: reward-payment-app:1.0.1
    ports:
      - "8090:8090"
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    command: ["sh", "-c", "chmod +x /wait-for-it.sh && /wait-for-it.sh reward-payment-db:3306 --timeout=30 -- java -jar /reward-payment-app.jar --spring.profiles.active=mysql-container"]
    depends_on:
      - reward-payment-db