name: build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build


#      - name: Update status
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_TO }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: |
#            Commit from: ${{ github.actor }}
#            Commit message: ${{ github.event.commits[0].message }}
#            Commit changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

#      - uses: yanzay/notify-telegram@v0.1.0
#        if: always()
#        with:
#            chat: ${{ secrets.TELEGRAM_TO }} # user id or channel name secret
#            token: ${{ secrets.TELEGRAM_TOKEN }} # token secret
#            status: ${{ job.status }} # do not modify this line
